site_name: MOCK-UP
nav:
    - Home: home.md
    - Code: code.md
    - Tutorials: tutorials.md
    - Resources: resources.md
    - Contact: contact.md
    - Français: https://siu-kevin.github.io/maquette/accueil
not_in_nav:
    index.md
theme:
    name: mkdocs
    custom_dir: custom_theme/
    locale: en
    color_mode: dark
    nav_style: dark
    user_color_mode_toggle: false
extra_css: [style.css]
plugins:
    - search
