site_name: mock-up
nav:
    - Home: index.md
    - About: about_en.md
theme:
    name: mkdocs
    locale: en
    color_mode: dark
    nav_style: dark
    user_color_mode_toggle: false
extra_css: [style.css]
plugins: []