site_name: MOCK-UP
nav:
    - Home: home.md
    - Code: code.md
    - Tutorial: tutorial.md
    - Other: other.md
    - Contact: contact.md
    - French Example: about_en.md
theme:
    name: mkdocs
    custom_dir: custom_theme/
    locale: en
    color_mode: dark
    nav_style: dark
    user_color_mode_toggle: false
extra_css: [style.css]
